apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lra-coordinator
  labels:
    app: lra-coordinator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lra-coordinator
  template:
    metadata:
      labels:
        app: lra-coordinator
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: coordinator
          image: local-coordinator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
              name: http
          env:
            - name: QUARKUS_HTTP_PORT
              value: "8090"
            - name: QUARKUS_TRANSACTION_MANAGER_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: QUARKUS_DATASOURCE_TX_LOG_DB_KIND
              value: postgresql
            - name: QUARKUS_DATASOURCE_TX_LOG_JDBC_URL
              value: jdbc:postgresql://postgres:5432/lra
            - name: QUARKUS_DATASOURCE_TX_LOG_USERNAME
              value: lra
            - name: QUARKUS_DATASOURCE_TX_LOG_PASSWORD
              value: lra
            - name: QUARKUS_TRANSACTION_MANAGER_OBJECT_STORE_TYPE
              value: jdbc
            - name: QUARKUS_TRANSACTION_MANAGER_OBJECT_STORE_DATASOURCE
              value: TX_LOG
            - name: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
              value: "true"
            - name: QUARKUS_TRANSACTION_MANAGER_OBJECT_STORE_CREATE_TABLE
              value: "true"
            - name: QUARKUS_DATASOURCE_TX_LOG_JDBC_TRANSACTIONS
              value: "disabled"

          readinessProbe:
            httpGet:
              path: /lra-coordinator
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /lra-coordinator
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["sh","-c","sleep 5"]
---
apiVersion: v1
kind: Service
metadata:
  name: lra-coordinator
spec:
  selector:
    app: lra-coordinator
  ports:
    - name: http
      port: 8090
      targetPort: 8090
  type: ClusterIP
