package io.narayana.lra.ha.participants;

public enum InjectPoint {
    START,
    JOIN_BEFORE_SAVE,
    JOIN_AFTER_SAVE,
    JOIN_BEFORE_DEACTIVATE,
    JOIN_AFTER_DEACTIVATE,
    JOIN_BEFORE_RESPONSE,
    JOIN_AFTER_RESPONSE_APPEND,
    END_BEFORE_SAVE,
    END_AFTER_SAVE,
    END_DURING_CLEANUP,
    END_AFTER_CLEANUP,
    END_AFTER_PARTICIPANT_RESPONSE,
    LEAVE_BEFORE_SAVE,
    LEAVE_AFTER_SAVE
}
